### ISSUE TITLE
Tiny feature modification

### ISSUE THREAD

**Issue by michael1006** [notjosh/Outside#2]
I absolutely love this screensaver! It's so fascinating.

Wanted to request a tiny feature modification, however -- right now it shows the location and creator when a video starts, but they disappear after a few seconds.

Since it's a screensaver, I'm not always (or usually) seeing the start of a video, but when I glance at my screen as I sit down at see a beautiful view, I really wonder where it is, but there's no way to ever know since the info has disappeared.

So I'd like to request that the location, at least, remain always visible.

(Or if some people want just the pure video, then a checkbox to enable the location overlay or not?)

Thanks so much! This screensaver is seriously just the absolute most interesting thing. I can't tell you enough how fascinating and educational it is to look out windows from across the whole world.

**Comment by notjosh** [comment]
Agreed! I've wanted this for a while myself, but had mild paranoia about monitor burn-in. I might have it swap between corners from time to time, which should solve the issue?

Hold that thought! :)

**Comment by notjosh** [comment]
Want to give 0.3.0 ([link](https://github.com/notjosh/Outside/releases/tag/v0.3.0)) a go? It'll keep the overlay in the same place for each video, and rotate corners for the next video. That'll do the job, I think!

Let me know if you bump into any issues.

**Comment by michael1006** [comment]
That's amazing! Just installed, works perfectly. Really awesome. I love looking at a scene, trying to guess which country, then checking the corner.

Also great idea about rotating corners -- I use to use the Aerial screensaver a lot and that has the same option, it randomly picks which corner to show the label on.

Thanks again!!
